In [1]:
%load_ext autoreload
%autoreload 2
%env CUDA_VISIBLE_DEVICES=0

env: CUDA_VISIBLE_DEVICES=0

In [ ]:
from omegaconf import OmegaConf
import pandas as pd
import os

In [14]:
project_dir = '/gpfs01/berens/user/inwabufo/leverage/leverage-data'

CLEANED_FILE = 'log_dir/areds_new_results_cleaned_03_06_26_split_id_11042026.csv'
metadata_dir = os.path.join(project_dir, 'metadata')
metadata_file = "surv_jul_data0_11_04_26.csv"
log_dir = 'log_dir'
hostname_ = 'CIN'
dataset_name = 'areds_new'
split_id = 11042026

config_file = '/gpfs01/berens/user/inwabufo/.secrets.yaml'
cfg = OmegaConf.load(config_file)
stylef = cfg['stylef'][hostname_]
CHKPT_DIR = chkpt_dir = os.path.join(project_dir, 'chkpt_dir', 'npj_areds_curves')
RESULTS_DIR = os.path.join(project_dir, 'results')
img_dir = cfg['DATASETS'][hostname_][dataset_name]
stylef = cfg['stylef'][hostname_]

In [15]:
surv_file = os.path.join(metadata_dir, metadata_file)
df = pd.read_csv(surv_file)
df.head()

/tmp/ipykernel_920312/3180318200.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(surv_file)

,patient_id,eye_id,image_id,visit_number,image_eye,image_field,image_side,image_file,image_path,diagnosis_amd_grade,...,clinical_treatment_category,clinical_laser_photocoagulation_right,clinical_laser_photocoagulation_left,diagnosis_final_amd_status,clinical_centrum_intake,patient_age,sequence_id,observation_id,duration,event
0,1001,1001_left,1001_left_RS_04,4,left,F2,RS,51685_04_F2_LE_RS.jpg,51685/51685_04_F2_LE_RS.jpg,3.0,...,4.0,N,N,6.0,N,74.4,1001_left,1001_left_4,16,0
1,1001,1001_left,1001_left_LS_06,6,left,F2,LS,51685_06_F2_LE_LS.jpg,51685/51685_06_F2_LE_LS.jpg,3.0,...,4.0,N,N,6.0,N,75.4,1001_left,1001_left_6,14,0
2,1001,1001_left,1001_left_LS_08,8,left,F2,LS,51685_08_F2_LE_LS.jpg,51685/51685_08_F2_LE_LS.jpg,2.0,...,4.0,N,N,6.0,N,76.4,1001_left,1001_left_8,12,0
3,1001,1001_left,1001_left_RS_10,10,left,F2,RS,51685_10_F2_LE_RS.jpg,51685/51685_10_F2_LE_RS.jpg,4.0,...,4.0,N,N,6.0,N,77.5,1001_left,1001_left_10,10,0
4,1001,1001_left,1001_left_LS_14,14,left,F2,LS,51685_14_F2_LE_LS.jpg,51685/51685_14_F2_LE_LS.jpg,6.0,...,4.0,N,N,6.0,N,80.1,1001_left,1001_left_14,6,0

In [16]:
df['patient_id'] = df['patient_id'].astype(str)

In [19]:
df_grp = df.groupby(['eye_id']).agg(list).reset_index()
df_grp.head(1)

,eye_id,patient_id,image_id,visit_number,image_eye,image_field,image_side,image_file,image_path,diagnosis_amd_grade,...,clinical_treatment_category,clinical_laser_photocoagulation_right,clinical_laser_photocoagulation_left,diagnosis_final_amd_status,clinical_centrum_intake,patient_age,sequence_id,observation_id,duration,event
0,1001_left,"[1001, 1001, 1001, 1001, 1001, 1001, 1001]","[1001_left_RS_04, 1001_left_LS_06, 1001_left_L...","[4, 6, 8, 10, 14, 16, 20]","[left, left, left, left, left, left, left]","[F2, F2, F2, F2, F2, F2, F2]","[RS, LS, LS, RS, LS, RS, LS]","[51685_04_F2_LE_RS.jpg, 51685_06_F2_LE_LS.jpg,...","[51685/51685_04_F2_LE_RS.jpg, 51685/51685_06_F...","[3.0, 3.0, 2.0, 4.0, 6.0, 8.0, 6.0]",...,"[4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0]","[N, N, N, N, N, N, N]","[N, N, N, N, N, N, N]","[6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0]","[N, N, N, N, N, N, N]","[74.4, 75.4, 76.4, 77.5, 80.10000000000001, 81...","[1001_left, 1001_left, 1001_left, 1001_left, 1...","[1001_left_4, 1001_left_6, 1001_left_8, 1001_l...","[16, 14, 12, 10, 6, 4, 0]","[0, 0, 0, 0, 0, 0, 0]"

In [20]:
df.shape, df_grp.shape

((55173, 28), (8784, 28))

In [21]:
8784*12

105408